---
- name: Check Yocto OS version
  hosts: yocto_devices
  gather_facts: no
  tasks:
    - name: Get /etc/os-release content
      ansible.builtin.shell: cat /etc/os-release
      register: os_release_output

    - name: Show OS release info
      ansible.builtin.debug:
        msg: |
          {{ inventory_hostname }} ({{ ansible_host }}):
          {{ os_release_output.stdout }}
